// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/4/2025, 11:46:26 PM
const configMerger = require("/Users/milindranjan/Desktop/Work/JRDARCHITECTS/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/milindranjan/Desktop/Work/JRDARCHITECTS/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/layouts/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/pages/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/composables/**/*.{js,ts,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/utils/**/*.{js,ts,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/{A,a}pp.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/{E,e}rror.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/JRDARCHITECTS/app.config.{js,ts,mjs}"] } }));

module.exports = config
