// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/4/2025, 5:45:03 PM
const configMerger = require("/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/layouts/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/pages/**/*.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/composables/**/*.{js,ts,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/utils/**/*.{js,ts,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/{A,a}pp.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/{E,e}rror.{vue,js,mjs}","/Users/milindranjan/Desktop/Work/Academics/JRDArchitects/app.config.{js,ts,mjs}"] } }));

module.exports = config
